# Generated by Django 2.0 on 2017-12-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
